name: Deploy to Gradio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install huggingface-cli
        run: |
          pip install huggingface_hub

      - name: Configure huggingface-cli
        run: |
          huggingface-cli login --token ${{ secrets.HUGGING_FACE_TOKEN }}

      - name: Deploy to Gradio
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
          GRADIO_APP_ID: ${{ secrets.GRADIO_APP_ID }}
        run: |
          # Force-push to Hugging Face Hub
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add huggingface https://huggingface:${HUGGING_FACE_TOKEN}@huggingface.co/${GRADIO_APP_ID}.git
          git fetch huggingface
          git reset --hard origin/main