name: Deploy to Gradio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install huggingface-cli
        run: |
          pip install huggingface_hub

      - name: Configure huggingface-cli
        run: |
          echo "Hugging Face Token: ${{ secrets.HUGGING_FACE_TOKEN }}"
          echo "Gradio App ID: ${{ secrets.GRADIO_APP_ID }}"
          huggingface-cli login --token ${{ secrets.HUGGING_FACE_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Hugging Face remote
        run: |
          git remote add huggingface https://huggingface:${{ secrets.HUGGING_FACE_TOKEN }}@huggingface.co/usiddiquee786/nyc-taxi-trip

      - name: Fetch and reset to main
        run: |
          git fetch huggingface
          git reset --hard origin/main

      - name: Push to Hugging Face Hub
        run: |
          git push huggingface main --force