name: Deploy to Gradio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Gradio
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
          GRADIO_APP_ID: ${{ secrets.GRADIO_APP_ID }}
        run: |
          # Install the Hugging Face Hub client library
          pip install huggingface_hub

          # Login to the Hugging Face Hub
          huggingface-cli login --token $HUGGING_FACE_TOKEN

          # Push the Gradio app to the Hugging Face Hub
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated deployment from GitHub Actions"
          git push https://huggingface:${HUGGING_FACE_TOKEN}@git.huggingface.co/${GRADIO_APP_ID}.git main

          # Update the Gradio app on the Hugging Face Hub
          huggingface-cli gradio update --app-id $GRADIO_APP_ID --model-id $GRADIO_APP_ID --commit-message "Automated deployment from GitHub Actions"